name: Deploy to Neocities

env:
    FORCE_COLOR: 1
    NODE_VERSION: lts/*

concurrency:
    group: deploy-to-neocities
    cancel-in-progress: true

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository code
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: false

            - name: Install dependencies and build site
              run: |
                  pnpm install --frozen-lockfile
                  pnpm run build

            - name: Deploy to Neocities
              uses: bcomnes/deploy-to-neocities@master
              with:
                  api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
                  cleanup: false
                  dist_dir: dist
                  api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
